apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-learning
  template:
    metadata:
      labels:
        app: k8-learning
    spec:
      containers:
        - name: k8-learning
          image: meirfuces/k8-learning:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS

                  
                  
        

---
apiVersion: v1
kind: Service
metadata:
  name: k8-learning
spec:
  type: NodePort
  selector:
    app: k8-learning
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 