apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-learning
  template:
    metadata:
      labels:
        app: k8-learning
    spec:
      containers:
        - name: k8-learning
          image: k8-learning:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: k8-learning
spec:
  type: NodePort
  selector:
    app: k8-learning
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 